# Generated by Django 5.2.18 on 2026-10-07 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('especie', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('AVE', 'Ave'), ('ROEDOR', 'Roedor'), ('OTRO', 'Otro')], default='PERRO', max_length=10)),
                ('raza', models.CharField(blank=True, max_length=60)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('VETERINARIO', 'Veterinario'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('especialidades', models.ManyToManyField(blank=True, related_name='veterinarios', to='clinica.especialidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=12)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('veterinario', models.ForeignKey(limit_choices_to={'perfil__rol': 'VETERINARIO'}, on_delete=django.db.models.deletion.PROTECT, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='clinica.mascota')),
            ],
            options={
                'ordering': ['fecha_hora'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'CANCELADA'), _negated=True), fields=('veterinario', 'fecha_hora'), name='cita_unica_por_veterinario_y_hora')],
            },
        ),
    ]
